FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY backend/ ./backend/
RUN mvn clean package -DskipTests -pl backend/monolito-service -am

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/backend/monolito-service/target/*.jar app.jar
EXPOSE 10000
ENV SERVER_PORT=10000
ENV JAVA_TOOL_OPTIONS="-Xmx300m -Xss512k -XX:TieredStopAtLevel=1 "
ENTRYPOINT ["java", "-jar", "app.jar"]
