services:
  - type: web
    name: tampur-monolito
    env: docker
    dockerfilePath: Dockerfile.monolito
    envVars:
      - key: SUPABASE_DB_URL
        value: "pendiente"
      - key: SUPABASE_DB_USER
        value: "pendiente"
      - key: SUPABASE_DB_PASSWORD
        value: "pendiente"
      - key: SENDGRID_API_KEY
        value: "pendiente"
