services:
  - type: web
    name: tampur-reservas-service
    env: docker
    plan: free
    dockerfilePath: Dockerfile.reservas
    envVars:
      - key: SUPABASE_DB_URL
        value: "pendiente"
      - key: SUPABASE_DB_USER
        value: "pendiente"
      - key: SUPABASE_DB_PASSWORD
        value: "pendiente"

  - type: web
    name: tampur-pagos-service
    env: docker
    plan: free
    dockerfilePath: Dockerfile.pagos
    envVars:
      - key: SUPABASE_DB_URL
        value: "pendiente"
      - key: SUPABASE_DB_USER
        value: "pendiente"
      - key: SUPABASE_DB_PASSWORD
        value: "pendiente"
      - key: SENDGRID_API_KEY
        value: "pendiente"

  - type: web
    name: tampur-backoffice-service
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backoffice
    envVars:
      - key: SUPABASE_DB_URL
        value: "pendiente"
      - key: SUPABASE_DB_USER
        value: "pendiente"
      - key: SUPABASE_DB_PASSWORD
        value: "pendiente"
